version: "3.3"

services:
  mamut-app-translator:
    container_name: mamut-app-translator
    build:
      context: ./
      dockerfile: ./docker/translator/dev.Dockerfile
    ports:
      - 8400:3000
    volumes:
      - ./src/translator/:/app/
    restart: always
    links:
      - "mamut-app-mysql:mysql"

  mamut-app-backend:
    container_name: mamut-app-backend
    build:
      context: ./
      dockerfile: ./docker/backend/dev.Dockerfile
    ports:
      - 8311:3000
      - 8080:8080
    volumes:
      - ./src/backend/:/app/
    restart: always
    links:
      - mamut-app-db:mongo

  mamut-app-parser:
    container_name: mamut-app-parser
    build:
      context: ./
      dockerfile: ./docker/backend/dev.Dockerfile
    ports:
      - 8312:3000
    volumes:
      - ./src/parser/:/app/
      - ./scripts/:/scripts/
    restart: always
    links:
      - mamut-app-db:mongo

  mamut-app-db:
    container_name: mamut-app-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongodb:/data/db:rw
      - ./logs/mongodb:/var/log/mongodb:rw
      - ./src/mongodb/scripts/:/scripts/:rw
    ports:
      - 27018:27017

  mamut-app-db-view:
    container_name: mamut-app-db-view
    image: mongo-express:0.49.0
    restart: always
    ports:
      - 8314:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    links:
      - mamut-app-db:mongo

  mamut-app-frontend:
    container_name: mamut-app-frontend
    image: node:14.5.0
    command: /bin/sh /app/scripts/run-react.sh
    stdin_open: true
    ports:
      - 8401:3000
    volumes:
      - ./src/frontend/:/app/
    restart: always

  mamut-app-frontend-parser:
    container_name: mamut-app-frontend-parser
    image: node:14.5.0
    command: /bin/sh /app/scripts/run-react.sh
    stdin_open: true
    ports:
      - 8501:3000
    volumes:
      - ./src/frontend_parser/:/app/
    restart: always

  mamut-app-mysql:
    container_name: mamut-app-mysql
    image: mysql:5.7.17
    command: mysqld --sql_mode="ONLY_FULL_GROUP_BY,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - /mnt/praca/Imagho/Data/mamut-app/mysql:/var/lib/mysql

  phpmyadmin:
    container_name: mamut-app-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 9215:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    links:
      - "mamut-app-mysql:mysql"
