version: "3.3"

services:
  mamut-app-mysql-8.0:
    container_name: mamut-app-mysql-8.0
    image: mysql:8.0
    command: mysqld --sql_mode="ONLY_FULL_GROUP_BY,NO_ENGINE_SUBSTITUTION" --log_bin_trust_function_creators=1
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-8.0:/var/lib/mysql
      - ./src/mysql-8.0/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./src/mysql-8.0/scripts/:/scripts/:rw

  phpmyadmin-mysql-8.0:
    container_name: mamut-app-phpmyadmin-mysql-8.0
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 9215:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    links:
      - "mamut-app-mysql-8.0:mysql"
    restart: always
