version: "3.3"

services:
  mamut-app-mysql:
    container_name: mamut-app-mysql
    image: mysql:5.7.17
    command: mysqld --sql_mode="ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - /mnt/praca/Imagho/Data/mamut-app/mysql:/var/lib/mysql
phpmyadmin:
  container_name: mamut-app-phpmyadmin
  image: phpmyadmin/phpmyadmin:latest
  ports:
    - 9215:80
  environment:
    PMA_HOST: mysql
    PMA_PORT: 3306
  links:
    - "mamut-app-mysql:mysql"
  restart: always
